#### Unifi ###################################################################################################
#------------------------------------------------------------------------------------------------------------#
- platform: unifi
  username: !secret unifi_username
  password: !secret unifi_password
  host: !secret unifi_host
  port: !secret unifi_port
  verify_ssl: false
  consider_home: 180


#### Ping ####################################################################################################
#------------------------------------------------------------------------------------------------------------#
- platform: ping
  hosts:
    ping_study_pc: !secret main_pc_host
    ping_ross_phone: !secret ross_phone_host
    ping_becks_phone: !secret becks_phone_host


#### iCloud ##################################################################################################
#------------------------------------------------------------------------------------------------------------#
- platform: icloud
  username: !secret icloud_user
  password: !secret icloud_pass

  
#### Google Maps #############################################################################################
#------------------------------------------------------------------------------------------------------------# 
- platform: google_maps
  username: !secret googlemaps_user
  password: !secret googlemaps_pass